import type { DriftReport, Mismatch } from "./types";
import { countBySeverity } from "./drift";

const SEVERITY_EMOJI: Record<string, string> = {
  high: "🔴",
  medium: "🟡",
  low: "⚪",
};

/** Format one mismatch as a Markdown block suitable for a GitHub issue. */
export function mismatchToMarkdown(m: Mismatch): string {
  const emoji = SEVERITY_EMOJI[m.severity] ?? "•";
  const lines: string[] = [];
  lines.push(`### ${emoji} ${m.title}  \`${m.severity}\``);
  lines.push("");
  if (m.description) {
    lines.push(m.description);
    lines.push("");
  }
  lines.push("**In the code:**");
  lines.push("```");
  lines.push(m.code_snippet || "(see source)");
  lines.push("```");
  lines.push("");
  lines.push("**In the docs:**");
  lines.push("```");
  lines.push(m.docs_snippet || "(not documented)");
  lines.push("```");
  lines.push("");
  if (m.suggested_fix) {
    lines.push(`**Suggested fix:** ${m.suggested_fix}`);
    lines.push("");
  }
  if (m.file) {
    lines.push(`_Source: \`${m.file}\`_`);
    lines.push("");
  }
  return lines.join("\n");
}

/** Build the full Markdown body of a "docs drift" issue for a report. */
export function reportToIssueMarkdown(
  report: DriftReport,
  selected?: Mismatch[],
): string {
  const mismatches = selected ?? report.mismatches;
  const counts = countBySeverity(mismatches);
  const lines: string[] = [];

  lines.push(
    `Found ${mismatches.length} place${
      mismatches.length === 1 ? "" : "s"
    } where the documentation no longer matches the code` +
      ` (drift score **${report.driftScore}/10** — ${report.scoreLabel}).`,
  );
  lines.push("");
  lines.push(
    `Severity breakdown: ${counts.high} high · ${counts.medium} medium · ${counts.low} low.`,
  );
  lines.push("");
  lines.push(`- **Repository:** ${report.repo.url}`);
  lines.push(`- **Docs analyzed:** ${report.docs.url}`);
  lines.push(`- **Branch:** \`${report.repo.branch}\``);
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const m of mismatches) {
    lines.push(mismatchToMarkdown(m));
    lines.push("---");
    lines.push("");
  }

  lines.push(
    "_Generated by [docsParity](https://github.com/reetbatra/docs-drift-detector) — " +
      "it compares a repo's public API surface against its published docs._",
  );

  return lines.join("\n");
}

function issueTitle(report: DriftReport, single?: Mismatch): string {
  if (single) {
    return `docs: ${single.title}`;
  }
  return `docs: ${report.mismatches.length} documentation mismatches (drift ${report.driftScore}/10)`;
}

/**
 * Build a GitHub "new issue" URL with the title + body pre-filled. Clicking it
 * drops the maintainer straight into a ready-to-submit issue. This is the
 * detail that turns an audit tool into a contribution tool.
 */
export function buildIssueUrl(report: DriftReport, single?: Mismatch): string {
  const base = `${report.repo.url}/issues/new`;
  const title = issueTitle(report, single);
  const body = single
    ? singleMismatchBody(report, single)
    : reportToIssueMarkdown(report);

  const params = new URLSearchParams({
    title,
    body,
    labels: "documentation",
  });
  return `${base}?${params.toString()}`;
}

function singleMismatchBody(report: DriftReport, m: Mismatch): string {
  const lines: string[] = [];
  lines.push(
    `While following the docs at ${report.docs.url}, the documentation appears to no longer match the code in ${report.repo.url}.`,
  );
  lines.push("");
  lines.push(mismatchToMarkdown(m));
  lines.push("");
  lines.push(
    "_Surfaced by docsParity, which diffs a repo's public API surface against its published docs._",
  );
  return lines.join("\n");
}
